1. Create two 3×3 matrices using the random function in Numpy and perform the following operations

Product

In [17]:
import numpy as np

x =  np.random.randint(1,10,(3,3))
y = np.random.randint(1, 10, (3,3))
print(x)
print(y)

product = np.prod(x)
print("Product of the matrix1 is : ",product)


[[6 4 4]
 [2 4 3]
 [3 2 9]]
[[1 8 3]
 [7 6 9]
 [4 6 2]]
Product of the matrix1 is :  124416


Multiplication

In [19]:
x =  np.random.randint(1,10,(3,3))
y = np.random.randint(1, 10, (3,3))
print(x)
print(y)
multiply = np.multiply(x,y)
print("Multiplication of two matrices are : ")
print(multiply)

[[8 4 5]
 [5 9 4]
 [1 4 6]]
[[2 5 8]
 [3 8 8]
 [5 4 4]]
Multiplication of two matrices are : 
[[16 20 40]
 [15 72 32]
 [ 5 16 24]]


Dot

In [20]:
x =  np.random.randint(1,10,(3,3))
y = np.random.randint(1, 10, (3,3))
print(x)
print(y)

dot = np.dot(x,y)
print("Dot of product : ")
print(dot)

[[6 5 3]
 [6 2 3]
 [6 6 3]]
[[4 8 7]
 [1 2 1]
 [7 2 8]]
Dot of product : 
[[50 64 71]
 [47 58 68]
 [51 66 72]]


Q2. Perform the following set operations using the Numpy functions.


UNION

In [11]:
set1 = np.array([1,2,3,4,5])
set2 = np.array([7,4,3,2,10,])
print(set1,set2)
result = np.union1d(set1,set2)
print("Union : ", result)

[1 2 3 4 5] [ 7  4  3  2 10]
Union :  [ 1  2  3  4  5  7 10]


INTERSECTION

In [10]:
set1 = np.array([1,2,3,4,5])
set2 = np.array([7,4,3,2,10,])
print(set1,set2)
result = np.intersect1d(set1,set2)
print("Intersection :" , result)

[1 2 3 4 5] [ 7  4  3  2 10]
Intersection [2 3 4]


SET DIFFERENCE

In [12]:
set1 = np.array([1,2,3,4,5])
set2 = np.array([7,4,3,2,10,])
print(set1,set2)
result = np.setdiff1d(set1,set2)
print("Set Difference :" , result)

[1 2 3 4 5] [ 7  4  3  2 10]
Set Difference : [1 5]


XOR


In [21]:
set1 = np.array([1,2,3,4,5])
set2 = np.array([7,4,3,2,10,])
print(set1, set2)
result = np.setxor1d(set1,set2)
print("XOR :" , result)

[1 2 3 4 5] [ 7  4  3  2 10]
XOR : [ 1  5  7 10]


Q3. Create a 1D array using Random function and perform the following operations.


CUMULATIVE SUM

In [23]:
arr1 = np.random.randint(1,10,size=10)
print("Original Array : ", arr1)

cumulative_sum = np.cumsum(arr1)
print("Cumulative sum : ", cumulative_sum)

Original Array :  [3 8 6 7 1 9 2 3 2 4]
Cumulative sum :  [ 3 11 17 24 25 34 36 39 41 45]


CUMULATIVE PRODUCT

In [25]:
arr1 = np.random.randint(1,10,size=10)
print("Original Array : ", arr1)

cumulative_prod = np.cumprod(arr1)
print("Cumulative product : ",cumulative_prod)

Original Array :  [4 7 2 3 1 6 9 5 3 7]
Cumulative product :  [     4     28     56    168    168   1008   9072  45360 136080 952560]


 Discrete difference (with n=3)

In [29]:
arr1 = np.random.randint(1,10,size=10)
print("Original Array : ", arr1)

discrete_diff = np.diff(arr1,n=3)
print("Cumulative product : ",discrete_diff)

Original Array :  [5 6 7 7 6 2 3 2 7 3]
Cumulative product :  [ -1   0  -2   8  -7   8 -15]


 Find the unique elements from the array

In [27]:
arr1 = np.random.randint(1,10,size=10)
print("Original Array : ", arr1)

unique = np.unique(arr1)
print("Cumulative product : ",unique)

Original Array :  [3 5 1 8 3 9 7 7 5 3]
Cumulative product :  [1 3 5 7 8 9]


Q4. Create two 1D array and perform the Addition using zip(), add() and user defined function (frompyfunc())

In [33]:
array1 = np.array([1,2,3,4,5])
array2 = np.array([10,20,30,40,50])

result = [x + y for x,y in zip(array1,array2)]
print("Addition using zip() : ", result)

add  = np.add(array1,array2)
print("Addition using np.add() : ", add)

def custom_add(x,y):
    return x+y

ufunc = np.frompyfunc(custom_add,2,1)
res = ufunc(array1,array2)
print("Addition using user defined function : ",res)


Addition using zip() :  [11, 22, 33, 44, 55]
Addition using np.add() :  [11 22 33 44 55]
Addition using user defined function :  [11 22 33 44 55]


Q5. Find the LCM (Least Common Multiple) and GCD (Greatest Common Divisor) of an array of elements using reduce()

In [36]:
from numpy import gcd, lcm
from functools import reduce

elements = np.array([16, 18, 24, 36])

lcm_result = reduce(lcm, elements)
print("LCM of elements:", lcm_result)

gcd_result = reduce(gcd, elements)
print("GCD of elements:", gcd_result)

LCM of elements: 144
GCD of elements: 2
