#### Q1. Write a program to distinguish between Array Indexing and Fancy Indexing.

In [3]:
## ARRAY INDEXING
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

index = int(input("Enter an index"))
print(f'Value at arr[{index}] = {arr[index]}')


[1 2 3 4 5]
Value at arr[2] = 3


In [10]:
## FANCY INDEXING

import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)

indexList = [0,2,3]

print(f'Using Fancy Indexing:')
print(f'arr[{indexList[0]}], arr[{indexList[1]}], arr[{indexList[2]}] : {arr[indexList]}')

[1 2 3 4 5]
Using Fancy Indexing:
arr[0], arr[2], arr[3] : [1 3 4]


#### Q2. Execute the 2D array Slicing.

In [14]:
import numpy as np

arr = np.random.randint(1,10, (5,5))
print(arr)
print()
print(arr[1,0:2])

print()
print(arr[0:3, 1:3])

[[6 3 9 7 2]
 [9 9 7 4 6]
 [4 7 6 3 8]
 [8 4 4 5 2]
 [4 5 6 3 6]]

[9 9]

[[3 9]
 [9 7]
 [7 6]]


#### Q3. Create the 5-Dimensional arrays using ‘ndmin’.

In [15]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,4], ndmin = 5)
print(arr)

print(f'Dimension of the array is: {arr.ndim}')

[[[[[1 2 3 4 5 6 7 8 4]]]]]
Dimension of the array is: 5


Q4. Reshape the array from 1-D to 2-D array.

In [17]:
import numpy as np

arr = np.array([1,22,13,34,45,2], ndmin=1)
print(arr)
print("After Reshaping")
newarr = arr.reshape(3,2)
print(newarr)

[ 1 22 13 34 45  2]
After Reshaping
[[ 1 22]
 [13 34]
 [45  2]]


#### Q5. Perform the Stack functions in Numpy arrays – Stack(), hstack(), vstack(), and dstack().

In [19]:
### STACK() IMPLEMENTATION

import numpy as np

arr1 = np.array([10,20,30])
arr2 = np.array([50,60,70])

newarr1 = np.stack((arr1,arr2), axis = 1)
newarr2 = np.stack((arr1,arr2), axis = 0)

print(newarr1)
print()
print(newarr2)

[[10 50]
 [20 60]
 [30 70]]

[[10 20 30]
 [50 60 70]]


In [20]:
###  HSTACK()

arr1 = np.array([10,20,30])
arr2 = np.array([50,60,70])

result = np.vstack((arr1,arr2))

print(result)

[[10 20 30]
 [50 60 70]]


In [21]:
###  hstack() Implementation

arr1 = np.array([10,20,30])
arr2 = np.array([50,60,70])

res = np.hstack((arr1,arr2))
print(res)

[10 20 30 50 60 70]


In [22]:
### dstack() Implementation

arr1 = np.array([10,20,30])
arr2 = np.array([50,60,70])

res = np.dstack((arr1,arr2))
print(res)

[[[10 50]
  [20 60]
  [30 70]]]


#### Q6. Perform the searchsort method in Numpy array.

In [25]:
import numpy as np

arr = np.array([1,4,5,8,9,10,23])
print(arr)

index = np.searchsorted(arr,7)

print(f'7 Can be inserted at index: {index}')



[ 1  4  5  8  9 10 23]
7 Can be inserted at index: 3


#### Q7. Create Numpy Structured array using your domain features.

In [67]:
import numpy as np

expenses = np.array([
    [100,200,6000],
    [200,150,3000],
    [50,170,2500],
    [70,200,3500],
    [80,250,2200],
])
print("\t\t\tDaily Expense ")
for i in range(len(expenses)):
    
    print(f"Expense of day {i+1} : ")
    print(f"\tMorning: {expenses[i][0]}")
    print(f"\tAfternoon: {expenses[i][1]}")
    print(f"\tEvening: {expenses[i][2]}")




			Daily Expense 
Expense of day 1 : 
	Morning: 100
	Afternoon: 200
	Evening: 6000
Expense of day 2 : 
	Morning: 200
	Afternoon: 150
	Evening: 3000
Expense of day 3 : 
	Morning: 50
	Afternoon: 170
	Evening: 2500
Expense of day 4 : 
	Morning: 70
	Afternoon: 200
	Evening: 3500
Expense of day 5 : 
	Morning: 80
	Afternoon: 250
	Evening: 2200


#### Q8. Create Data frame using List and Dictionary.

In [11]:
import pandas as pd

df = pd.read_csv("personal_expense_data.csv")

print("Lists:")
print("Description for the 1st 10 Events : ", list(df["Description"][:10]))
print("Category Fee for the 1st 10 Events : ", list(df["Category"][:10]))

print("\nDictionary:")
for index, row in df.head(10).iterrows():
    data_dict = {
        "Description": row["Description"],
        "Category": row["Category"],
        "Amount": row["Amount"],
        
    }
    print(data_dict)


Lists:
Description for the 1st 10 Events :  ['Open-architected bi-directional database', 'Multi-channeled regional portal', 'Customizable bi-directional array', 'Networked 5thgeneration Internet solution', 'Operative multimedia capability', 'Advanced secondary Local Area Network', 'Up-sized impactful monitoring', 'Future-proofed empowering alliance', 'Multi-lateral multimedia moratorium', 'Streamlined encompassing open system']
Category Fee for the 1st 10 Events :  ['Dining Out', 'Housing', 'Housing', 'Housing', 'Housing', 'Transportation', 'Transportation', 'Housing', 'Transportation', 'Groceries']

Dictionary:
{'Description': 'Open-architected bi-directional database', 'Category': 'Dining Out', 'Amount': 1525.3}
{'Description': 'Multi-channeled regional portal', 'Category': 'Housing', 'Amount': 9198.75}
{'Description': 'Customizable bi-directional array', 'Category': 'Housing', 'Amount': 5525.0}
{'Description': 'Networked 5thgeneration Internet solution', 'Category': 'Housing', 'Amou

#### Q9. Create Data frame on your Domain area and perform the following operations to find and eliminate the missing data from the dataset.
• isnull()
• notnull()
• dropna()
• fillna()
• replace()
• interpolate()

In [26]:
### isnull()
 
import pandas as pd
import numpy as np


df = pd.read_csv("personal_expense_data.csv")

# print("Original DataFrame:")
# print(df)


print("\nChecking for missing data using isnull():")
print(df.isnull())


Checking for missing data using isnull():
      Date  Description  Category  Amount  Expense Type  Payment Method  \
0    False        False     False   False         False           False   
1    False        False     False   False         False           False   
2    False        False     False   False         False           False   
3    False        False     False   False         False           False   
4    False        False     False   False         False           False   
..     ...          ...       ...     ...           ...             ...   
245  False        False     False   False         False           False   
246  False        False     False   False         False           False   
247  False        False     False   False         False           False   
248  False        False     False   False         False           False   
249  False        False     False   False         False           False   

     Payment Status  Account/Bank  Tags/Labels  Notes  


In [29]:
## notnull()
print("\nChecking for non-missing data using notnull():")
print(df.notnull())


Checking for non-missing data using notnull():
     Date  Description  Category  Amount  Expense Type  Payment Method  \
0    True         True      True    True          True            True   
1    True         True      True    True          True            True   
2    True         True      True    True          True            True   
3    True         True      True    True          True            True   
4    True         True      True    True          True            True   
..    ...          ...       ...     ...           ...             ...   
245  True         True      True    True          True            True   
246  True         True      True    True          True            True   
247  True         True      True    True          True            True   
248  True         True      True    True          True            True   
249  True         True      True    True          True            True   

     Payment Status  Account/Bank  Tags/Labels  Notes  
0      

In [28]:
# dropna()
print("\nDropping rows with missing data using dropna():")
df_dropna = df.dropna()
print(df_dropna)


Dropping rows with missing data using dropna():
           Date                                Description        Category  \
0    2022-09-23   Open-architected bi-directional database      Dining Out   
1    2023-01-21            Multi-channeled regional portal         Housing   
2    2023-03-17          Customizable bi-directional array         Housing   
3    2022-10-29  Networked 5thgeneration Internet solution         Housing   
4    2023-01-01            Operative multimedia capability         Housing   
..          ...                                        ...             ...   
245  2022-12-14          Switchable user-facing moratorium  Transportation   
246  2022-12-27         Function-based tangible moratorium         Housing   
247  2023-01-17                Versatile mobile capability  Transportation   
248  2022-09-28          Triple-buffered coherent leverage       Groceries   
249  2023-06-09      Universal non-volatile knowledge user      Dining Out   

      Amount E

In [31]:
# fillna()
print("\nFilling missing data using fillna():")
df_fillna = df.fillna(0)  
print(df_fillna)


Filling missing data using fillna():
           Date                                Description        Category  \
0    2022-09-23   Open-architected bi-directional database      Dining Out   
1    2023-01-21            Multi-channeled regional portal         Housing   
2    2023-03-17          Customizable bi-directional array         Housing   
3    2022-10-29  Networked 5thgeneration Internet solution         Housing   
4    2023-01-01            Operative multimedia capability         Housing   
..          ...                                        ...             ...   
245  2022-12-14          Switchable user-facing moratorium  Transportation   
246  2022-12-27         Function-based tangible moratorium         Housing   
247  2023-01-17                Versatile mobile capability  Transportation   
248  2022-09-28          Triple-buffered coherent leverage       Groceries   
249  2023-06-09      Universal non-volatile knowledge user      Dining Out   

      Amount Expense Type

In [32]:
#  replace()
print("\nReplacing missing data using replace():")
df_replace = df.replace(np.nan, -1)  
print(df_replace)


Replacing missing data using replace():
           Date                                Description        Category  \
0    2022-09-23   Open-architected bi-directional database      Dining Out   
1    2023-01-21            Multi-channeled regional portal         Housing   
2    2023-03-17          Customizable bi-directional array         Housing   
3    2022-10-29  Networked 5thgeneration Internet solution         Housing   
4    2023-01-01            Operative multimedia capability         Housing   
..          ...                                        ...             ...   
245  2022-12-14          Switchable user-facing moratorium  Transportation   
246  2022-12-27         Function-based tangible moratorium         Housing   
247  2023-01-17                Versatile mobile capability  Transportation   
248  2022-09-28          Triple-buffered coherent leverage       Groceries   
249  2023-06-09      Universal non-volatile knowledge user      Dining Out   

      Amount Expense T

In [33]:
# interpolate()
print("\nInterpolating missing data using interpolate():")
df_interpolate = df.interpolate()
print(df_interpolate)


Interpolating missing data using interpolate():
           Date                                Description        Category  \
0    2022-09-23   Open-architected bi-directional database      Dining Out   
1    2023-01-21            Multi-channeled regional portal         Housing   
2    2023-03-17          Customizable bi-directional array         Housing   
3    2022-10-29  Networked 5thgeneration Internet solution         Housing   
4    2023-01-01            Operative multimedia capability         Housing   
..          ...                                        ...             ...   
245  2022-12-14          Switchable user-facing moratorium  Transportation   
246  2022-12-27         Function-based tangible moratorium         Housing   
247  2023-01-17                Versatile mobile capability  Transportation   
248  2022-09-28          Triple-buffered coherent leverage       Groceries   
249  2023-06-09      Universal non-volatile knowledge user      Dining Out   

      Amount E

C:\Users\super\AppData\Local\Temp\ipykernel_24872\4227306499.py:3: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_interpolate = df.interpolate()


#### Q10. Perform the Hierarchical Indexing in the above created dataset.

In [24]:
import pandas as pd

df = pd.read_csv("personal_expense_data.csv")

# Set hierarchical indexing
df.set_index(['Description', 'Category'], inplace=True)

# # Display the DataFrame with hierarchical indexing
print("DataFrame with Hierarchical Indexing:")
print(df)

DataFrame with Hierarchical Indexing:
                                                                Date   Amount  \
Description                               Category                              
Open-architected bi-directional database  Dining Out      2022-09-23  1525.30   
Multi-channeled regional portal           Housing         2023-01-21  9198.75   
Customizable bi-directional array         Housing         2023-03-17  5525.00   
Networked 5thgeneration Internet solution Housing         2022-10-29  2096.87   
Operative multimedia capability           Housing         2023-01-01   394.39   
...                                                              ...      ...   
Switchable user-facing moratorium         Transportation  2022-12-14  9134.36   
Function-based tangible moratorium        Housing         2022-12-27  1081.73   
Versatile mobile capability               Transportation  2023-01-17  8951.91   
Triple-buffered coherent leverage         Groceries       2022-09-28  4